### ISSUE TITLE
Add support for optional trailing slash.

### ISSUE THREAD

**Issue by akshatvg** [AgoraIO-Community/agora-token-service#17]
Go Gin supports optional trailing slashes in the API endpoints. 

I faced a CORS error and did not realise for some time that this was because I missed a / in the endpoint on the client side. 

On the server side, there was a 301 response which was a redirect internally within Go.  

If we could make it optional, it would be a good enhancement.

**Comment by akshatvg** [comment]
`api.RedirectTrailingSlash = false`

Adding this to line 39 temporary solved my problem and helped me realise the issue as the redirects stopped and the API returned 404 which is the expected response for a wrong endpoint.

**Comment by maxxfrazer** [comment]
Sorry you didn't get a response earlier, just picking up this project now and I'm not seeing the issue from postman or my own browser. Setting setting the redirect to false causes problems though, are you still facing this issue?
