### ISSUE TITLE
Generating Subscriber token type fails

### ISSUE THREAD

**Issue by galblank** [AgoraIO-Community/agora-token-service#29]
When trying to generate token type SUBSCRIBER
`const Role = {
    // for live broadcaster
    PUBLISHER: 1,

    // default, for live audience
    SUBSCRIBER: 2,
};`
Getting error 
`Unhandled error TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received type number (0)
    at new NodeError (internal/errors.js:322:7)
    at Function.from (buffer.js:334:9)
    at Object.ByteBuf.that.putString (/workspace/agora/AccessToken2.js:318:37)
    at ServiceRtc.pack (/workspace/agora/AccessToken2.js:63:47)
    at /workspace/agora/AccessToken2.js:233:65
    at Array.forEach (<anonymous>)
    at AccessToken2.build (/workspace/agora/AccessToken2.js:232:38)
    at Function.buildTokenWithUserAccount (/workspace/agora/RtcTokenBuilder2.js:64:22)
    at Function.buildTokenWithUid (/workspace/agora/RtcTokenBuilder2.js:31:21)
    at /workspace/agoratoken.js:34:39 {
  code: 'ERR_INVALID_ARG_TYPE'`
  
  Generation Code : 
  `const channelName = uid;
  const tokenTTL = 60 * 60 * 23; // 23 hours

  const expires = Date.now() + (tokenTTL * 1000);
  const expiresInSeconds = Math.floor(expires / 1000);
  const viewerToken = RtcTokenBuilder.buildTokenWithUid(
    appID,
    appCertificate,
    channelName,
    0,
    RtcRole.SUBSCRIBER,
    expiresInSeconds,
  );
  console.log("Viewer token: " + viewerToken);`

**Comment by maxxfrazer** [comment]
Looks like this question is more for [go-tokenbuilder](https://github.com/AgoraIO-Community/go-tokenbuilder), unless you're also not able to generate a subscriber token using this project?
@plutoless may know more about how the token builder works.

**Comment by galblank** [comment]
For some reason , the issue turned out to be 
`const {RtcTokenBuilder, RtcRole} = require('agora-access-token');` works 
while the example in the Agora  dashboard doesnt

**Comment by maxxfrazer** [comment]
@galblank we should probably change that then. where in the dashboard do you see that?

What you have now looks similar to that given in the docs:
https://docs.agora.io/en/video-calling/develop/integrate-token-generation?platform=react-native#handle-the-system-logic

**Comment by maxxfrazer** [comment]
i believe this issue is resolved, please re-open if that’s not the case
