### ISSUE TITLE
Fixed Error on token: but Can use the UIKit on assembleRelease mode. Works on debug mode only...

### ISSUE THREAD

**Issue by jrcity** [AgoraIO-Community/agora-token-service#30]
I am using the agora-rn-uikit and this is how my component is
import AgoraUIKit from 'agora-rn-uikit';
import { PropsInterface } from 'agora-rn-uikit/src/Contexts/PropsContext';
import React, { memo } from 'react';
import { SafeAreaView } from 'react-native';

import { agora_appid } from '@env';

const Call = ({ route }) => {
	console.log(route)
	const CONFIG: PropsInterface = {
		callbacks: {
			EndCall: () => {},
		},
		rtcProps: {
			appId: agora_appid,
			channel: 'test',
			tokenUrl: 'https://agora-token-server-yxfs.onrender.com'
			// channel: route.params.channel,
			// token: route.params.token,
			// token: '006f02c42153ca346a69b4495043c8491a6IAB1h7fK9rpjoAb0H7OYBJvnca/iUQUf8BG2DeCgQR57RuAS44q379yDIgDERRUFANzHYwQAAQCQmMZjAgCQmMZjAwCQmMZjBACQmMZj'
			// tokenUrl: 'https://agora-token-service-production-c1ac.up.railway.app'
		},
		rtmProps: {
		},
		rtmCallbacks: {},
	};
	return (
		<SafeAreaView style={{ flex: 1 }}>
			<AgoraUIKit
				connectionData={CONFIG.rtcProps}
				settings={{
					displayUsername: true,
				}}
			// rtcCallbacks={CONFIG.callbacks}
			/>
		</SafeAreaView>
	);
};

export default memo(Call);

# and
when I use the tokenUrl props I done even get any response. the ui will just be blank black

Can anyone suggest how I use the token generated properly??

**Comment by maxxfrazer** [comment]
@Jrcity what version of the RN UI Kit are you using? @EkaanshArora may be able to help.
Check on railway/render if there are any logs on your instance.
Also, does the code work if you manually add the token that's shown above or does that also give a black screen?

**Comment by EkaanshArora** [comment]
Are you using the latest version of the UIKit & the SDK?

**Comment by jrcity** [comment]
> Are you using the latest version of the UIKit & the SDK?

yes I am. I have fixed this. The problem was I am using one uid for the audiences.

another thing is that I can not use the videostream on assemblerelease mode. Its working fine in debug mode.
 Whenever I enter the video screen the apps closes.

**Comment by EkaanshArora** [comment]
can you describe the error with `assembleRelease` mode?

**Comment by jrcity** [comment]
> can you describe the error with `assembleRelease` mode?

okay After I've testing the uikit in react-native debugging mode between two devices, everything works fine

So I build the app into an apk and tried to see if it can be used in production but when I tried to create a call it will close as soon as the I press the joining button.

**Comment by EkaanshArora** [comment]
can you share the logs from the crash?

**Comment by jrcity** [comment]
There are no logs after building to an apk right?

The apk builds successfully but after install the app on my devices (both real phone and simulator) I try to make a call it closes the app.

I don't know how to generate a log report on a built apk app file.

**Comment by jrcity** [comment]
> There are no logs after building to an apk right?
> 
> The apk builds successfully but after install the app on my devices (both real phone and simulator) I try to make a call it closes the app.
> 
> I don't know how to generate a log report on a built apk app file.

I Think I messed up not AgoraUIKit. I just tried to implement it again this time around just the uikit and I built it to an apk file then install it. everything works fine.

Thank you @EkaanshArora  and @maxxfrazer  for the assist.
