### ISSUE TITLE
Allow Cors as Environment Variable

### ISSUE THREAD

**Issue by maxxfrazer** [AgoraIO-Community/agora-token-service#40]
Default value `"*"`

**Comment by VictorRed** [comment]
I get CORS exception when trying to request for a Token, is this the same issue ?

**Comment by maxxfrazer** [comment]
> I get CORS exception when trying to request for a Token, is this the same issue ?

yes it likely is, i’ll add this to the one-click setups today

**Comment by maxxfrazer** [comment]
@VictorRed give that a go, please feel free to re-open this issue if there's any other CORS issues.

**Comment by rkirimov** [comment]
@maxxfrazer I think CORS_ALLOW_ORIGIN also needs to be added to Dockerfile as ARG/ENV

**Comment by digitallysavvy** [comment]
@rkirimov this issue is resolved in the latest updates in PR #56
