### ISSUE TITLE
Heroku 404

### ISSUE THREAD

**Issue by slacker-jake** [AgoraIO-Community/agora-token-service#61]
Hi,

I deployed using Heroku but I'm getting a 404 error when I open the app.

![image](https://github.com/user-attachments/assets/18972619-3f63-4fa2-99ff-6f60f3e743a2)

Everything seemed to deploy ok.  I left a * in the CORS_ALLOW_ORIGIN variable.

**Comment by digitallysavvy** [comment]
Thanks for flagging this @slacker-jake, the team will take a look and update the ticket once we have more information. Is Heroku support a blocker for your team, or are you able to use one of the other quick deploy options?

**Comment by slacker-jake** [comment]
Hi, I tried Railway today and also receive the 404 message

**Comment by slacker-jake** [comment]
Any update for us?  Do you also see the issue on your end?

**Comment by digitallysavvy** [comment]
@slacker-jake, I tested the quick deploys and they are all working. Are you using the /ping endpoint to test the resource? 
Can you walk me through your issue? Please include the urls you are using that return the 404 errors. 

`<server-url>/ping` should return `{"message":"pong"}`

**Comment by slacker-jake** [comment]
I haven't tried myself but my developer has stated its working now.  Thanks!
